/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as IndexDesignRouteImport } from './routes/indexDesign'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as ProviderRouteImport } from './routes/provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDesignRoute = IndexDesignRouteImport.update({
  id: '/indexDesign',
  path: '/indexDesign',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/indexDesign': typeof IndexDesignRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRoute
  '/provider': typeof ProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/indexDesign': typeof IndexDesignRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRoute
  '/provider': typeof ProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/indexDesign': typeof IndexDesignRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRoute
  '/provider': typeof ProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/get-started'
    | '/indexDesign'
    | '/onboarding'
    | '/patient'
    | '/provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/get-started'
    | '/indexDesign'
    | '/onboarding'
    | '/patient'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/get-started'
    | '/indexDesign'
    | '/onboarding'
    | '/patient'
    | '/provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GetStartedRoute: typeof GetStartedRoute
  IndexDesignRoute: typeof IndexDesignRoute
  OnboardingRoute: typeof OnboardingRoute
  PatientRoute: typeof PatientRoute
  ProviderRoute: typeof ProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexDesign': {
      id: '/indexDesign'
      path: '/indexDesign'
      fullPath: '/indexDesign'
      preLoaderRoute: typeof IndexDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GetStartedRoute: GetStartedRoute,
  IndexDesignRoute: IndexDesignRoute,
  OnboardingRoute: OnboardingRoute,
  PatientRoute: PatientRoute,
  ProviderRoute: ProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
